layout_spectrum: 0.9569892
typography_spectrum: 0.6648746
color:
  saturation: 0.7275985
  lightness: 1
  brandStrength: 0.4749104
  rhythmicContrast: 0.1505376
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: KayMedia
